name: My GitHub Actions Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2

      - name: Clone iis-lab2 repository
        run: git clone https://github.com/Sl33px/iis-lab2.git

      - name: Build code
        run: echo "Build step goes here"
