name: Copy files from iis-lab2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo (iis_lab5)
        uses: actions/checkout@v2

      - name: Clone iis-lab2 repository
        run: git clone https://github.com/Sl33px/iis-lab2.git

      - name: Copy files from iis-lab2 to iis_lab5
        run: |
          cp -r iis-lab2/* ./
          cp -r iis-lab2/.* ./ || true  # на випадок .gitignore або .env
          rm -rf ./iis-lab2             # прибрати клонований репо після копіювання

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Автоматичне копіювання з iis-lab2" || echo "No changes to commit"
          git push
